version: "3.8"
services:
  web:
    image: rpungello/laravel-nginx
    ports:
      - "${WEB_PORT:-80}:80"
    volumes:
      - ".:/var/www/html"
    restart: unless-stopped
    depends_on:
      - app
  app:
    image: rpungello/laravel-app:7.4
    volumes:
      - ".:/var/www/html"
    restart: unless-stopped
