name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        version: ['7.4', '8.2', '8.3']
        type: ['full', 'min']
    name: ${{ matrix.os }} - P${{ matrix.version }}/${{ matrix.type }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Compose
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose-${{ matrix.version }}-${{ matrix.type }}.yml"
